### ISSUE TITLE
What to do with 'squatted' name?

### ISSUE THREAD

**Issue by kotborealis** [dtolnay/squatternaut#4]
I accidentally found myself on this list, as 'squatting' [crates.io/asciichart](https://crates.io/crates/asciichart)
Apparently, about 2 or 3 years ago I had an idea to make something, pushed an empty crate and completely forgot about it.

The question is: what should I actually do with this crate? I guess crates.io does not allow to delete published crates.
Should I take some time to actually make something useful and publish it under this name?

**Comment by dtolnay** [comment]
It's going to stay on the list until someone else decides they want to use this name, they contact you about it (your email and twitter are accessible from your GitHub profile), you reassign ownership of the name to them, and they publish their project.
